version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: censopcd
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: user

  web:
    build: .
    container_name: php_apache_container
    restart: always
    volumes:
      - ./projeto/:/var/www/html
    ports:
      - '80:80'

volumes:
  db_data:
